import ProjectDescription

let workspace = Workspace(
    name: "BasicModularApp",
    projects: ["./**"],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes:
                .enabled(codeCoverageMode: .all,
                         testingOptions: [.randomExecutionOrdering])
    )
)
 //
// .targets(["Numbers"])
