import ProjectDescription

let workspace = Workspace(
    name: "BasicModularApp",
    projects: ["./**"],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes:
                .enabled(codeCoverageMode: .targets(["Numbers"]),
                         testingOptions: [.randomExecutionOrdering])
    )
)
