import ProjectDescription

let workspace = Workspace(
    name: "AppWithPartialCoverage",
    projects: ["./**"],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes:
                .enabled(codeCoverageMode: .all,
                         testingOptions: [.randomExecutionOrdering])
    )
)
